[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
opacity = 0.95

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
