format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$rust\
$nodejs\
$golang\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "

[rust]
format = "[$symbol($version)]($style) "

[nodejs]
format = "[$symbol($version)]($style) "

[golang]
format = "[$symbol($version)]($style) "
